// Code generated by mockery v2.10.1. DO NOT EDIT.

package mocks

import (
	bytes "bytes"

	mock "github.com/stretchr/testify/mock"
)

// ImageStore is an autogenerated mock type for the ImageStore type
type ImageStore struct {
	mock.Mock
}

// Save provides a mock function with given fields: taskID, imageType, imageData
func (_m *ImageStore) Save(taskID string, imageType string, imageData bytes.Buffer) (string, error) {
	ret := _m.Called(taskID, imageType, imageData)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, bytes.Buffer) string); ok {
		r0 = rf(taskID, imageType, imageData)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, bytes.Buffer) error); ok {
		r1 = rf(taskID, imageType, imageData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
