// Code generated by mockery v2.10.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isUploadImageRequest_Data is an autogenerated mock type for the isUploadImageRequest_Data type
type isUploadImageRequest_Data struct {
	mock.Mock
}

// isUploadImageRequest_Data provides a mock function with given fields:
func (_m *isUploadImageRequest_Data) isUploadImageRequest_Data() {
	_m.Called()
}
