// Code generated by mockery v2.10.1. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	taskpb "github.com/fgmaia/task/pb/taskpb"
)

// TaskServiceClient is an autogenerated mock type for the TaskServiceClient type
type TaskServiceClient struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: ctx, in, opts
func (_m *TaskServiceClient) CreateTask(ctx context.Context, in *taskpb.CreateTaskRequest, opts ...grpc.CallOption) (*taskpb.CreateTaskResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *taskpb.CreateTaskResponse
	if rf, ok := ret.Get(0).(func(context.Context, *taskpb.CreateTaskRequest, ...grpc.CallOption) *taskpb.CreateTaskResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*taskpb.CreateTaskResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *taskpb.CreateTaskRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
