// Code generated by mockery v2.10.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeTaskServiceServer is an autogenerated mock type for the UnsafeTaskServiceServer type
type UnsafeTaskServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedTaskServiceServer provides a mock function with given fields:
func (_m *UnsafeTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {
	_m.Called()
}
